# Generated by Django 3.2 on 2021-05-12 13:40

import award.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('lecturers', models.ManyToManyField(to='award.Lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[award.models.validate_ovgu])),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.lecturer')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.module')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.student')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lecturer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique fullname'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.UniqueConstraint(fields=('lecturer', 'module', 'student'), name='unique nomination'),
        ),
    ]
