# Generated by Django 3.2 on 2021-05-18 21:01

import award.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('MB', 'Maschinenbau'), ('EIT', 'Elektro- & Informationstechnik'), ('VST', 'Verfahrens- & Systemtechnik'), ('IN', 'Informatik'), ('WW', 'Wirtschaftswissenschaften'), ('HW', 'Humanwissenschaften'), ('NW', 'Naturwissenschaften'), ('ME', 'Medizin'), ('MA', 'Mathematik')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('sub_email', models.EmailField(max_length=254, validators=[award.models.validate_domain])),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('verified', models.BooleanField(default=False)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.lecturer')),
            ],
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('token', models.CharField(default=award.models.generate_token, max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('expiration', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.nomination')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lecturer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique_fullname'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.CheckConstraint(check=models.Q(sub_email__iregex='^[\\.0-9a-z]+@(st\\.)?ovgu\\.de$'), name='check_domain_whitelist'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.UniqueConstraint(condition=models.Q(sub_email__iregex='^[\\.0-9a-z]+@(st\\.)?ovgu\\.de$'), fields=('lecturer', 'sub_email'), name='unique_nomination'),
        ),
    ]
