# Generated by Django 3.2 on 2021-05-17 21:12

import award.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('faculty', models.CharField(choices=[('MB', 'Maschinenbau'), ('EIT', 'Elektro- & Informationstechnik'), ('VST', 'Verfahrens- & Systemtechnik'), ('IN', 'Informatik'), ('WW', 'Wirtschaftswissenschaften'), ('HW', 'Humanwissenschaften'), ('NW', 'Naturwissenschaften'), ('ME', 'Medizin'), ('MA', 'Mathematik')], max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Nomination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('sub_email', models.EmailField(max_length=254, validators=[award.models.validate_ovgu])),
                ('sub_date', models.DateTimeField(auto_now_add=True)),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.lecturer')),
            ],
        ),
        migrations.AddConstraint(
            model_name='lecturer',
            constraint=models.UniqueConstraint(fields=('first_name', 'last_name'), name='unique fullname'),
        ),
        migrations.AddConstraint(
            model_name='nomination',
            constraint=models.UniqueConstraint(fields=('lecturer', 'sub_email'), name='unique nomination'),
        ),
    ]
