# Generated by Django 3.2 on 2021-05-11 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nomination',
            old_name='submitter_email',
            new_name='sub_email',
        ),
        migrations.AddField(
            model_name='nomination',
            name='sub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
