# Generated by Django 3.2 on 2021-05-18 12:09

import award.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('key', models.CharField(default=award.models.generate_token, max_length=16, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), 'Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.', 'invalid')])),
                ('expiration', models.DateTimeField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='award.nomination')),
            ],
        ),
    ]
