# Generated by Django 3.2 on 2021-06-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_auto_20210519_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='faculty',
            field=models.CharField(choices=[('MB', 'Mechanical Engineering'), ('EIT', 'Electrical Engineering & Information Technology'), ('VST', 'Process & Systems Engineering'), ('IN', 'Computer Science'), ('WW', 'Economics and Management'), ('HW', 'Humanities, Social Science & Education'), ('NW', 'Natural Science'), ('ME', 'Medicine'), ('MA', 'Mathematics')], max_length=3),
        ),
    ]
