# Generated by Django 3.2 on 2021-06-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0003_alter_lecturer_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
